### ISSUE TITLE
How to configure the postlink

### ISSUE THREAD

**Issue by liemteksun** [Jenkler/nodebb-plugin-postlink#2] opened 2021-09-01 04:45 UTC
I am not an expert on NodeBB - I've installed & active this plug-in, but I can't find how to configure it on admin page
I even tried to enter the URL manually by going to <host>/admin/plugins/postlink-setting, but it doesn't work
Can you please tell me how I can change the setting?

Just FYI. I'm using NodeBB 1.17.2

thanks

**Comment by Jenkler** [comment] 2021-09-01 07:55
First, explain what you are trying to do.

This plugin modifies urls in posts that is external and adds the configured string before the url string.

Config:
https://www.google.com/q=

Then you urls will look like this
https://www.google.com/q=http://test.com

If the post url is http://test.com. This is useful if you want all your external links go through another site/proxy.

If the issue is that you can't access the admin page you need to activate the plugin and then rebuild nodebb from the ACP or command line nodebb build.

**Comment by liemteksun** [comment] 2021-09-01 08:00
Indeed this is what I'm trying to do
Every URL in the forum have my URL prefix and will add affiliate link (if available) before redirecting the user to that URL

I did rebuild nodebb from command line by calling this command
nodebb setup

thanks

**Comment by Jenkler** [comment] 2021-09-01 08:05
Nodebb setup is only for when you setup nodebb for the first time. Use nodebb build instead for rebuilding assets. You can also do this at the admin dashboard (restart and rebuild)

But your issue is that you can't see the admin plugin configuration page for postlink at all, right?

You can see how it works at https://www.uex.se

**Comment by liemteksun** [comment] 2021-09-01 08:21
I'm using a very slow machine to rebuild (nodebb build) - hopefully that works
But yes, the issue is I can't see the admin plugin configuration page for postlink

If it still doesn't work, is it possible to set the value manually?

**Comment by Jenkler** [comment] 2021-09-01 08:34
This plugin should work for your version. I will update it to 1.18.x soon.

This plugin only allow to set one postlink url for the whole site and it is not possible to set this without modifying the db or admin config page.

Do you get any error messages when running nodebb in dev mode? Does it load my plugin.
nodebb dev

**Comment by liemteksun** [comment] 2021-09-01 08:42
Thanks for your help
Unfortunately, my nodebb is not finish building yet, I have this problem from time to time because of cpu & memory constrain on the test server
I will try what you suggested and I think I just need to understand how to load the plug-in to nodebb
If I need more help particularly for this plug-in, I'll update this issue again

thanks for your help & for developing this plug-in

**Comment by Jenkler** [comment] 2021-09-01 08:50
I think you also need to run nodejs 14.x if you see any JavaScript errors from my plugin when debugging with nodebb dev.

I am closing this issue but you can contact me through info@jenkler.com regarding issues with this plugin.

Thanks for using my plugin ;)

**Closed as completed by Jenkler** 2021-09-01 08:50 UTC
